integrations:
  poplar-executables-pytorch-3-1:
    type: dataset
    ref: paperspace/dszxu7bmykjs7j0:6gd1pi5
  squad:
    type: dataset
    ref: paperspace/dsw2jrzd591wjrw:t6nyw3u
  ogbl_wikikg2_custom:
    type: dataset
    ref: paperspace/ds5fogtxxi0h935:wqp02u5
  poplar-executables-3-1-gptj:
    type: dataset
    ref: paperspace/dsk1tv1rcsvy1h2:3ci2mes
  gptj-6b-checkpoints:
    type: dataset
    ref: paperspace/dsftg00ynvrawou:m5z5tmm
  glue:
    type: dataset
    ref: paperpsace/dsalacr4p2hnbnq:ckb5h6e

