integrations:
  poplar-executables-pytorch-3-2:
    type: dataset
    ref: paperspace/
  squad:
    type: dataset
    ref: paperspace/dsw2jrzd591wjrw:t6nyw3u
  ogbl_wikikg2_custom:
    type: dataset
    ref: paperspace/ds5fogtxxi0h935:wqp02u5
  chest-xray-nihcc-3:
    type: dataset
    ref: paperspace/dsfzugibmi3rtyo:1mq8ehu
