integrations:
  poplar-executables-pytorch-3-1-1:
    type: dataset
    ref: paperspace/ds5ecae0no6sej4:z5ry8bd
  squad:
    type: dataset
    ref: paperspace/dsw2jrzd591wjrw:t6nyw3u
  ogbl_wikikg2_custom:
    type: dataset
    ref: paperspace/ds5fogtxxi0h935:wqp02u5
  poplar-executables-3-1-gptj:
    type: dataset
    ref: paperspace/dsk1tv1rcsvy1h2:3ci2mes
  gptj-6b-checkpoints:
    type: dataset
    ref: paperspace/dsftg00ynvrawou:3okp5u1
  glue:
    type: dataset
    ref: paperspace/dsalacr4p2hnbnq:ckb5h6e
  chest-xray-nihcc-3:
    type: dataset
    ref: paperspace/dsfzugibmi3rtyo:1mq8ehu
