integrations:
  poplar-executables-pytorch:
    type: dataset
    ref: paperspace/dsffz9mtb17vtim:iwybbh0
  squad:
    type: dataset
    ref: paperspace/dsw2jrzd591wjrw:t6nyw3u
  ogbl_wikikg2_custom:
    type: dataset
    ref: paperspace/ds5fogtxxi0h935:wqp02u5
